### ISSUE TITLE
SQL formatting options

### ISSUE THREAD

**Issue by frigus02** [frigus02/typescript-sql-tagged-template-plugin#16]
So amazing, really impressive work @frigus02 !! 🔥

Just giving it a spin, seems to be working!! I'm going to need to probably pass some additional configuration options to `pgFormatter` such as [`--comma-break`](https://github.com/darold/pgFormatter/blob/d5ffbbc/README#L32) (see screenshots below), but I suppose that will require:

1. Passing the option(s) along through `gajus/pg-formatter`, à la your PR at https://github.com/gajus/pg-formatter/pull/7
2. Setting this option in the `typescript-sql-tagged-template-plugin` and `vscode-sql-tagged-template-literals` (wonder if `--comma-break` should be even the default)

### `INSERT` without `--comma-break`

![Screen Shot 2020-11-28 at 16 32 09](https://user-images.githubusercontent.com/1935696/100519320-79e7f700-3197-11eb-845f-dad7b081283f.png)

### `INSERT` with `--comma-break`

![Screen Shot 2020-11-28 at 16 34 18](https://user-images.githubusercontent.com/1935696/100519385-cfbc9f00-3197-11eb-8b28-8c40b9dcf8a7.png)

Screenshot source: http://sqlformat.darold.net/

_Originally posted by @karlhorky in https://github.com/frigus02/typescript-sql-tagged-template-plugin/issues/4#issuecomment-735245346_

**Comment by frigus02** [comment]
Sorry for the delayed response @karlhorky. I'm moving home and the last few days have been super busy. I moved this into a new issue to make this more visible.

I agree that supporting all the different formatting options would be nice.

I see 2 different ways to do that:

1. Add every setting as a setting to this [pg-formatter](https://github.com/gajus/pg-formatter), this plugin and [the extension](https://github.com/frigus02/vscode-sql-tagged-template-literals/). This is nice the users but possibly quite a bit of maintenance effort.
2. Utilize the config file support. We could add 1 option: `--config FILE` to [pg-formatter](https://github.com/gajus/pg-formatter) and this plugin. The extension could possibly find a `.pg_format` file in the workspace root automatically and pass it in. This has the benefit that it automatically supports all pgFormatter options, including future options. But it's possibly slightly less convenient.

I think I would prefer the config file option or something that works similarly.

What do you think?

**Comment by karlhorky** [comment]
No worries at all! You've done amazing work. I hope that your move is going well!

Config file seems reasonable, sure! Through the single file (seems like [this is the format](https://github.com/darold/pgFormatter/blob/master/doc/pg_format.conf.sample)), it would support all options in one go, and have no maintenance effort in the future. Can probably close https://github.com/gajus/pg-formatter/issues/8 if this is a good way forward.

**Comment by frigus02** [comment]
Hi @karlhorky. I finally found some time to work on this. I published v0.1.1 of this package and v0.0.17 of the corresponding VS Code extension.

They now allow you to specify a pg_format config file, which means you have all pgFormatter options available, as seen in [pg_format.conf.sample](https://github.com/darold/pgFormatter/blob/v4.4/doc/pg_format.conf.sample). You probably want to stay away from some of them like `format=html` 😄. I tested `comma=start`, `comma-break=1` and `keyword-case` and they worked perfectly.

I hope this works for you as well 🤞

**Comment by karlhorky** [comment]
Hey @frigus02 , Happy New Year! 🎉✨  Hope the move went well and the year is starting off nicely!

Really awesome work! 🙌 Looks great - custom implementation of the `pgFormatter`, nice! 🤯

Now that all features are there and this is looking good, I've been thinking about how to enable this for our @upleveled students. At first I thought that I would configure the `TypeScript and JavaScript Language Features` as a second formatter for the students, but there are some downsides to this:

- [running Prettier alongside `TypeScript and JavaScript Language Features` is not currently possible with `vscode-format-code-action`](https://github.com/rohit-gohri/vscode-format-code-action/issues/4#issuecomment-738026556)
- running the formatting is kind of slow

So I thought of another approach - why not get the students to manually run the formatter on the command line once at the end, when they are ready to submit their projects? I can use this opportunity to fix other things / check for errors too, such as using ESLint with our [`eslint-config-upleveled`](https://github.com/upleveled/eslint-config-upleveled/).

So now a new interesting problem - how to use this TypeScript Language Service plugin on the command line?

I found the [Enabling a plugin](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#enabling-a-plugin) section, which mentions the `compilerOptions.plugins` configuration option in `tscconfig.json`, but I'm worried that this will not actually at any point call `getFormattingEditsForDocument` in this plugin since ["TypeScript Language Service Plugins are for changing the editing experience only [and not for applying transforms]"](https://github.com/microsoft/TypeScript/issues/16607). I did find [`ttypescript`](https://github.com/cevek/ttypescript), which seems to address the issue "Currently TypeScript doesn't support custom transformers in the `tsconfig.json`, but supports it programmatically."

So based on this, it looks like the best options for running this on the command line would be to either:

1. Use [`ttypescript`](https://github.com/cevek/ttypescript)
2. write my own custom Node script that uses `program.emit` kind of [like `angular` does](https://github.com/angular/angular/blob/d7665fdc96e30a21cf33c96fb0cc29a90404b5f9/packages/compiler-cli/src/transformers/program.ts#L76-L77)

...However, I'm unsure whether the API of a "transformer module" corresponds at all to the API exposed by `typescript-sql-tagged-template-plugin` - I fear it does not.

Would you have any other tips for running this in a command-line context?

Other things that I tried searching for (but which did not return anything that I could make sense of):

- running TypeScript Language Service Plugins on the command line
- running and interacting with a standalone `tsserver` from a Node.js script
  - this pointed me in the direction of [`theia-ide/typescript-language-server`](https://github.com/theia-ide/typescript-language-server/tree/master/example), but this was again about writing a client for a specific editor - I don't want the editor part

**Comment by karlhorky** [comment]
Hey @frigus02 , Happy New Year! 🎉✨  Hope the move went well and the year is starting off nicely!

Really awesome work! 🙌 💯 Looks great - custom implementation of the `pgFormatter`, nice! 🤯

**Comment by karlhorky** [comment]
Now that all features are there and this is looking good, I've been thinking about how to enable this for our @upleveled students. At first I thought that I would configure the `TypeScript and JavaScript Language Features` as a second formatter for the students, but there are some downsides to this:

- [running Prettier alongside `TypeScript and JavaScript Language Features` is not currently possible with `vscode-format-code-action`](https://github.com/rohit-gohri/vscode-format-code-action/issues/4#issuecomment-738026556)
- running the formatting is kind of slow

So I thought of another approach - why not get the students to manually run the formatter on the command line once at the end, when they are ready to submit their projects? I can use this opportunity to fix other things / check for errors too, such as using ESLint with our [`eslint-config-upleveled`](https://github.com/upleveled/eslint-config-upleveled/).

So now a new interesting problem - how to use this TypeScript Language Service plugin on the command line?

Since this was long and could result in a discussion that may be helpful for others, moved this to a new issue: https://github.com/frigus02/typescript-sql-tagged-template-plugin/issues/20

**Comment by frigus02** [comment]
Yeah, it would be amazing if formatting could be integrated with Prettier. But I think this would be  out of scope for this plugin.

**Comment by karlhorky** [comment]
> But I think this would be out of scope for this plugin

Definitely, for sure! This plugin is about extending the TypeScript Language Server, which makes sense for the plugin that is supporting a VS Code Extension.

There are efforts such as https://github.com/benjie/prettier-plugin-pg by @benjie to create a Prettier plugin, but I think the concerns are different enough (eg. the Prettier-specific AST) that the two approaches wouldn't have much overlap.

**Comment by benjie** [comment]
Prettier can use any AST I think (though some might need to be transformed a little); the main issue holding up prettier-plugin-pg is that comments are dropped by postgres' parser, and the postgres parser does not contain enough information about the location of the tokens that comments can be restored into the correct places even if we were to write a separate parallel parser just for comments. We need an alternative parser for PostgreSQL and I've not yet found one that I feel covers sufficient of Postgres' features without introducing issues (and a code formatter should _never_ break your code!). I'm interested in this though; maybe it'll be useful for [pg-sql2](https://www.npmjs.com/package/pg-sql2).
