### ISSUE TITLE
[REQUEST] Allow ignoring SQL validation issues with comment

### ISSUE THREAD

**Issue by stewartmcgown** [frigus02/typescript-sql-tagged-template-plugin#21]
Hi! Love the library.

We use this on quite a large project that uses TypeORM extensively. We have a number of custom SQL queries and queryBuilders that are essentially SQL fragments. It would be very useful if we could ignore SQL fragments to prevent them from showing req squiglies whilst still getting the gorgeous syntax highlighting.

One other issue is the way that the template variables in the string are found to be syntax errors as well. Obviously the library could never validate the content of a template variable, but again it would be good to ignore it on a case by case basis.

Another option instead of a comment would be to have a seperate sql literal that could be configured to _not_ do any validation, although I'm not sure if that's possible. I know one can disable the setting globally via `enableDiagnostics`, but we also need the ability to write full queries that do require validation.

An example of how we use it:

```ts
.addSelect(
            sql`COUNT(o.id) FILTER 
                 (WHERE (o.status = '${OrderStatus.PREP}' OR o.status = '${OrderStatus.AWAITING_RIDER}') AND o."isBeingOfferedToRider" = false)`,
            'orders_not_picked_up',
          )
          .addSelect(
            sql`COUNT(o.id) FILTER 
                 (WHERE o.status = '${OrderStatus.EN_ROUTE}')`,
            'orders_en_route',
          )
          .addSelect(
            sql`COUNT(o.id) FILTER 
                 (WHERE o."isRiderAtRestaurant" = true)`,
            'orders_rider_at_restaurant',
          )
```

![image](https://user-images.githubusercontent.com/1136276/104205581-79917b80-5426-11eb-9747-c048b53bb19c.png)

**Comment by frigus02** [comment]
Hi @stewartmcgown. One way I did that on a recent project was to name the function that produced only parts of an SQL statement differently. We used `sql` for functions that returned full SQL statements and `sqlFragment` for functions that returned only parts. We also made the return types different, so that we could not accidentally try to execute something returned by `sqlFragment`.

Because of that recent project, this extension currently adds syntax highlighting for functions called `sql` and `sqlFragment` but only does diagnostics for functions named `sql`.

It would be possible to make the name configurable that's used for diagnostics. But sadly the names used for syntax highlighting cannot be made configurable. I suppose we could add support for some kind of "ignore" comment.

What would you prefer? Is the different function name okay?

**Comment by stewartmcgown** [comment]
That sounds absolutely perfect. Did I miss that in the docs?

**Comment by frigus02** [comment]
No, you didn't. It's not in the docs. Good hint, though. I should really add that.
